/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { NFTTest__factory } from "./NFTTest__factory";
export { Receiver__factory } from "./Receiver__factory";
